# Generated by Django 2.1.7 on 2019-02-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190215_0757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollAdmin',
            new_name='Poll_admin',
        ),
    ]
