# Generated by Django 2.1.7 on 2019-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190215_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_nominated',
            field=models.BooleanField(null=True),
        ),
    ]
