# Generated by Django 2.1.7 on 2019-02-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190215_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_casted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='votes_received',
            field=models.IntegerField(default=0),
        ),
    ]
