# Generated by Django 2.1.7 on 2019-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190215_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_nominated',
            new_name='is_nominated_PM',
        ),
        migrations.AddField(
            model_name='user',
            name='is_nominated_councillor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nominated_mayor',
            field=models.BooleanField(null=True),
        ),
    ]
