# Generated by Django 2.1.7 on 2019-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190215_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vote_casted',
            new_name='vote_casted_PM',
        ),
        migrations.AddField(
            model_name='user',
            name='vote_casted_councillor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_casted_mayor',
            field=models.BooleanField(null=True),
        ),
    ]
