# Generated by Django 2.1.7 on 2019-02-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190215_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='votes_received',
            new_name='votes_count_PM',
        ),
        migrations.AddField(
            model_name='user',
            name='votes_count_councillor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='votes_count_mayor',
            field=models.IntegerField(default=0),
        ),
    ]
