# Generated by Django 2.1.7 on 2019-02-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_councillor_mayor_pm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Councillor',
            new_name='Councillor',
        ),
    ]
